name: Build frontend package
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: frikanalen/frontend-v2:${{ github.sha }},frikanalen/frontend-v2:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
